- name: rhel 7 content
  block:

  - set_fact:
      data_content_path: "{{ one }}"
      data_content_list: ["{{ two }}","{{ thr }}","{{ fou }}"]
    vars:
      one: 
        path: "{{ import_path }}/content/dist/rhel/server/{{ temp_os_major }}/{{ temp_os_major }}.{{ temp_os_minor }}/x86_64/kickstart"
      two: 
        path: "{{ import_path }}/content/dist/rhel/server/{{ temp_os_major }}/{{ temp_os_major }}.{{ temp_os_minor }}/x86_64"
        content: "kickstart"
      thr: 
        path: "{{ import_path }}/content/dist/rhel/server/{{ temp_os_major }}/{{ temp_os_major }}.{{ temp_os_minor }}"
        content: "x86_64"
      fou: 
        path: "{{ import_path }}/content/dist/rhel/server/{{ temp_os_major }}"
        content: "{{ temp_os_major }}.{{ temp_os_minor }}"

  - name: "create iso content import path"
    file: 
      path: "{{ data_content_path }}"
      recurse: true
      state: directory
      owner: foreman-proxy
      group: foreman-proxy

  - name: create listing file
    lineinfile:
      path: "{{ temp['path'] }}/listing"
      create: true
      #line: "{{ (temp['content'] | type_debug != 'List') | ternary(temp['content'], temp['content'] | join(',') ) }}"
      line: "{{ (temp['content'] }}"
      owner: foreman-proxy
      group: foreman-proxy
    loop_control:
      loop_var: temp
    loop: "{{ data_content_list }}"

  - name: "copy from iso mount to content repo***"
    copy:
      remote_src: true
      src:  "{{ temp }}"
      dest: "{{ data_content_path }}"
      owner: foreman-proxy
      group: foreman-proxy
    loop_control:
      loop_var: temp
    with_items:
    - "{{ files }}"
    - "{{ dir }}"
  when: (temp_os_major == '7')

- name: rhel 8 content
  include_tasks: rhel8_treeinfo.yml
  loop:
  - appstream
  - baseos
  loop_control:
    loop_var: item8  
  when: (temp_os_major == '8')
