- name: rhel 7 content
  block:

  - name: "create iso content import path"
    file: 
      path: "{{ data_content_path }}"
      recurse: true
      state: directory
      owner: foreman-proxy
      group: foreman-proxy
    vars:
      path: "{{ import_path }}/content/dist/rhel/server/{{ temp_os_major }}/{{ temp_os_major }}.{{ temp_os_minor }}/x86_64/kickstart"

  - name: "copy from iso mount to content repo***"
    copy:
      remote_src: true
      src:  "{{ temp }}"
      dest: "{{ data_content_path }}"
      owner: foreman-proxy
      group: foreman-proxy
    loop_control:
      loop_var: temp
    with_items:
    - "{{ files }}"
    - "{{ dir }}"
  when: (temp_os_major == '7')
  vars:
      data_content_path: "{{ import_path }}/content/dist/rhel/server/{{ temp_os_major }}/{{ temp_os_major }}.{{ temp_os_minor }}/x86_64/kickstart"

- name: rhel 8 content
  include_tasks: rhel8_treeinfo.yml
  loop:
  - appstream
  - baseos
  loop_control:
    loop_var: item8  
  when: (temp_os_major == '8')
