- set_fact:
    temp_repo_name:     "{{ item[1]['name'] }}"
    temp_iso_path:      "{{ item[1]['isos']['iso_path'] }}"
    temp_download_path: "{{ item[1]['isos']['download_path'] }}"

- name: "file check {{ download_path }}"
  file:
    path: "{{ temp_download_path }}"
    state: directory
    recurse: true

- name: grab iso file
  uri:
    url: "{{ temp_path }}{{ iso }}"
    user: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    force_basic_auth: true
    dest: "{{ temp_download_path }}"
  vars:
    iso:  "{{ temp_iso_path | split('/') | last }}"
    temp_path: "{{ repo_data | selectattr('name', 'equalto', temp_repo_name) | map(attribute='path') | first }}"

- name: "mounting {{ temp_iso_path }} to {{ temp_mount_path }}"
  mount:
    path:   "{{ temp_mount_path }}"
    src:    "{{ temp_iso_path }}"
    fstype: "iso9660"
    opts:   "ro,noauto"
    state:  "mounted"

- include_tasks: assert.yml

- include_tasks: file_path.yml

- include_tasks: find_files.yml

- name: "copy from iso mount to content repo***"
  copy:
    remote_src: true
    src:  "{{ temp }}"
    dest: "{{ data_content_path }}"
    owner: foreman-proxy
    group: foreman-proxy
  loop_control:
    loop_var: temp
  with_items:
  - "{{ files }}"
  - "{{ dir }}"
  when: item[1]['os_major'] == 7