- set_fact:
    temp_repo_name:     "{{ item[1]['name'] }}"
    temp_iso_path:      "{{ item[1]['isos']['iso_path'] }}"
    temp_download_path: "{{ item[1]['isos']['download_path'] }}"
    temp_iso_download:  "{{ temp_download_path }}/{{ item[1]['isos']['iso_path'] | split('/') | last }}"
    temp_os_major:      "{{ item[1]['isos']['os_major'] }}"
    temp_mount_path:    "{{ item[1]['isos']['mount_path'] }}"
    temp_os_major:      "{{ item[1]['isos']['os_major'] }}"
    temp_os_minor:      "{{ item[1]['isos']['os_minor'] }}"
  vars:
    temp_download_path: "{{ item[1]['isos']['download_path'] }}"

- name: "file check {{ temp_download_path }}"
  file:
    path: "{{ temp_download_path }}"
    state: directory
    recurse: true

- name: grab iso file
  get_url:
    url: "{{ temp_path }}{{ iso }}"
    username: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    force_basic_auth: true
    dest: "{{ temp_download_path }}"
  vars:
    iso:  "{{ temp_iso_path | split('/') | last }}"
    temp_path: "{{ repo_data | selectattr('name', 'equalto', temp_repo_name) | map(attribute='path') | first }}"
  when: skip | bool

- name: "mounting {{ temp_iso_path }} to {{ temp_mount_path }}"
  mount:
    path:   "{{ temp_mount_path }}"
    src:    "{{ temp_iso_path }}"
    fstype: "iso9660"
    opts:   "ro,noauto"
    state:  "mounted"

- include_tasks: assert.yml
  when: skip | bool

- include_tasks: find_files.yml

- include_tasks: file_path.yml

- name: "mounting {{ temp_iso_path }} to {{ temp_mount_path }}"
  mount:
    path:   "{{ temp_mount_path }}"
    src:    "{{ temp_iso_path }}"
    fstype: "iso9660"
    opts:   "ro,noauto"
    state:  "unmounted"