- set_fact:
    data_content_path: "{{ import_path }}/content/dist/rhel{{ temp_os_major }}/{{ temp_os_major }}.{{ temp_os_minor }}/x86_64/{{ item8 }}/kickstart"
 

- name: "create iso content import path"
  file:
     path: "{{ data_content_path }}/{{ item8 }}"
     recurse: true
     owner: foreman-proxy
     group: foreman-proxy
     state: directory

- name: add tree file to {{ item8 }}
  template:
    src: "{{ item8 }}.j2"
    dest: "{{ data_content_path }}/treeinfo"
    owner: foreman-proxy
    group: foreman-proxy
    mode: 0644

- name: copy {{ item8 }} to {{ data_content_path }}
  copy:
    src:  "{{ temp_mount_path }}/AppStream"
    dest: "{{ data_content_path }}"
    owner: apache
    group: apache
    remote_src: true
  when: (item8 == 'appstream')

- name: copy baseos data over to {{ data_content_path }}
  block:
  - set_fact:
      baseos: "{{ dir | difference(temp) }}"
    vars:
      temp: ["{{ temp_mount_path }}/AppStream","{{ temp_mount_path }}/BaseOS"]  

  - name: copy dirs to baseos
    copy:
      src:  "{{ temp_item }}"
      dest: "{{ data_content_path }}"
      owner: apache
      group: apache
      remote_src: true
    loop: "{{ baseos }}"
    loop_control:
      loop_var: temp_item

  - name: copy files to baseos
    copy:
      src:  "{{ temp_item }}"
      dest: "{{ data_content_path }}"
      owner: apache
      group: apache
      remote_src: true
    loop: "{{ files }}"
    loop_control:
      loop_var: temp_item
  when: (item8 == 'baseos')