- set_fact:
    data_content_path: "{{ import_path }}/content/dist/rhel{{ temp_os_major }}/{{ temp_os_major }}.{{ temp_os_minor }}/x86_64/{{ item8 }}/kickstart"
    data_content_list: ["{{ two }}","{{ thr }}","{{ fou }}"]
  vars:
      two: 
        path: "{{ import_path }}/content/dist/rhel{{ temp_os_major }}/{{ temp_os_major }}.{{ temp_os_minor }}/x86_64/appstream"
        content: "kickstart"
      thr: 
        path: "{{ import_path }}/content/dist/rhel{{ temp_os_major }}/{{ temp_os_major }}.{{ temp_os_minor }}/x86_64/baseos"
        content: "kickstart"
      fou: 
        path: "{{ import_path }}/content/dist/rhel{{ temp_os_major }}"
        content: "{{ temp_os_major }}.{{ temp_os_minor }}"

- name: create listing file
  lineinfile:
    path: "{{ temp['path'] }}/listing"
    create: true
    line: "{{ temp['content'] }}"
    owner: foreman-proxy
    group: foreman-proxy
  loop_control:
    loop_var: temp
  loop: "{{ data_content_list }}"

- name: "create iso content import path"
  file:
     path: "{{ data_content_path }}"
     recurse: true
     owner: foreman-proxy
     group: foreman-proxy
     state: directory

- name: copy {{ item8 }} to {{ data_content_path }}
  copy:
    src:  "{{ temp_mount_path }}/AppStream/"
    dest: "{{ data_content_path }}"
    owner: foreman-proxy
    group: foreman-proxy
    remote_src: true
  when: (item8 == 'appstream')

- name: copy baseos data over to {{ data_content_path }}
  block:
  - set_fact:
      baseos: "{{ dir | difference(temp) }}"
    vars:
      temp: ["{{ temp_mount_path }}/AppStream","{{ temp_mount_path }}/BaseOS"]  

  - name: copy dirs to baseos
    copy:
      src:  "{{ temp_item }}"
      dest: "{{ data_content_path }}"
      owner: foreman-proxy
      group: foreman-proxy
      remote_src: true
    loop: "{{ baseos }}"
    loop_control:
      loop_var: temp_item

  - name: copy files to baseos
    copy:
      src:  "{{ temp_item }}"
      dest: "{{ data_content_path }}"
      owner: foreman-proxy
      group: foreman-proxy
      remote_src: true
    loop: "{{ files }}"
    loop_control:
      loop_var: temp_item
  when: (item8 == 'baseos')

- name: add tree file to {{ item8 }}
  template:
    src: "{{ item8 }}.j2"
    dest: "{{ data_content_path }}/treeinfo"
    owner: foreman-proxy
    group: foreman-proxy
    mode: 0644