---
collections:
# With just the collection name
- name: theforeman.foreman
  source: https://galaxy.ansible.com
- name: git@github.com:TheRedGreek/remote_kickstart_installer.git
  source: git
- name: ansible.posix
