- name: "copy from iso mount to {{ foreman_server_url }}/pub/***"
  copy:
    src:  "{{ temp }}"
    dest: "{{ item['web_path'] }}"
    owner: apache
    group: apache
    remote_src: true
  vars:
    temp: "{{ item['mount_path'] }}/AppStream"

- name: "copy from iso mount to {{ foreman_server_url }}/pub/***"
  copy:
    src:  "{{ temp }}"
    dest: "{{ item['web_path'] }}"
    owner: apache
    group: apache
    remote_src: true
  vars:
    temp: "{{ item['mount_path'] }}/BaseOS"

- set_fact:
    baseos: "{{ dir | difference(temp) }}"
  vars:
    temp: ["{{ item['mount_path'] }}/AppStream","{{ item['mount_path'] }}/BaseOS"]  

- name: copy dirs to baseos
  copy:
    src:  "{{ temp_item }}"
    dest: "{{ rhel8['baseos_pulp_path'] }}"
    owner: apache
    group: apache
    remote_src: true
  loop: "{{ baseos }}"
  loop_control:
    loop_var: temp_item

- name: copy files to baseos
  copy:
    src:  "{{ temp_item }}"
    dest: "{{ rhel8['baseos_pulp_path'] }}"
    owner: apache
    group: apache
    remote_src: true
  loop: "{{ files }}"
  loop_control:
    loop_var: temp_item

- name: "copy pulp manifest"
  copy:
    src:  "8_appstream_pulp_manifest"
    dest: "{{ rhel8['appstream_pulp_path'] }}/PULP_MANIFEST"
    owner: apache
    group: apache

- name: "copy pulp manifest"
  copy:
    src:  "8_baseos_pulp_manifest"
    dest: "{{ rhel8['baseos_pulp_path'] }}/PULP_MANIFEST"
    owner: apache
    group: apache

- name: generate treeinfo
  template:
    src:  "{{ jinja_rhel8 }}"
    dest: "{{ rhel8['appstream_pulp_path'] }}/treeinfo"
    owner: apache
    group: apache
  vars:
    jinja_rhel8: AppStream.j2

- name: generate treeinfo
  template:
    src:  "{{ jinja_rhel8 }}"
    dest: "{{ rhel8['baseos_pulp_path'] }}/treeinfo"
    owner: apache
    group: apache
  vars:
    jinja_rhel8: BaseOS.j2
