- set_fact:
    os_major: "{{ item['os_major'] }}"
    os_minor: "{{ item['os_minor'] }}"

- name: "create the web path: {{ path['appstream_web_path'] }}"
  file:
    path: "{{ path['appstream_web_path'] }}"
    recurse: true
    state: directory

- name: "create the web path: {{ path['baseos_web_path'] }}"
  file:
    path: "{{ path['baseos_web_path'] }}"
    recurse: true
    state: directory

- name: "copy from iso mount to {{ foreman_server_url }}/pub/***"
  copy:
    remote_src: true
    src:  "{{ path['appstream_copy_path'] }}"
    dest: "{{ path['appstream_web_path'] }}"
    owner: apache
    group: apache

- name: "copy from iso mount to {{ foreman_server_url }}/pub/***"
  copy:
    remote_src: true
    src:  "{{ path['baseos_copy_path'] }}"
    dest: "{{ path['baseos_web_path'] }}"
    owner: apache
    group: apache

- name: "copy pulp manifest"
  copy:
    src:  "8_appstream_pulp_manifest"
    dest: "{{ path['appstream_web_path'] }}/PULP_MANIFEST"
    owner: apache
    group: apache

- name: "copy pulp manifest"
  copy:
    src:  "8_baseos_pulp_manifest"
    dest: "{{ path['baseos_web_path'] }}/PULP_MANIFEST"
    owner: apache
    group: apache

- name: generate treeinfo
  template:
    src:  "{{ jinja_path }}"
    dest: "{{ path['appstream_web_path'] }}/AppStream/treeinfo"
    owner: apache
    group: apache
  vars:
    jinja_path: AppStream.j2

- name: generate treeinfo
  template:
    src:  "{{ jinja_path }}"
    dest: "{{ path['baseos_web_path'] }}/BaseOS/treeinfo"
    owner: apache
    group: apache
  vars:
    jinja_path: BaseOS.j2
