- name: "copy from iso mount to web {{ foreman_server_url }}"
  ansible.copy:
    remote_src: true
    src:  "{{ item['copy_path'] }}"
    dest: "{{ item['web_path'] }}"
    ower: apache
    group: apache
  loop: "{{ item['kickstart_publish_paths'] }}"