- name: "copy from iso mount to {{ foreman_server_url }}/pub/***"
  copy:
    remote_src: true
    src:  "{{ item['copy_path'] }}"
    dest: "{{ item['web_path'] }}"
    owner: apache
    group: apache
  loop: "{{ item['kickstart_publish_paths'] | default([]) }}"