- name: "create directory path for temporary mount location"
  file:
    path: "{{ item['mount_path'] }}"
    recurse: true
    state: directory

- name: "create the web path: {{ item['web_path'] }}"
  file:
    path: "{{ item['web_path'] }}"
    recurse: true
    state: directory
  when: item['web_path'] is defined

- name: "verify  {{ item['iso_path'] }}"
  block:
  - stat: 
      path: "{{ item['iso_path'] }}"
    register: iso_type
    ignore_errors: true

  - set_fact:
      test: "application/x-iso9660-image"
      type: "{{ iso_test['stat']['mimetype'] | default(omit) }}"

  - assert:
      that:
      - type == test
      msg:
      - "!!! READ ME !!!"
      - "validate that {{ item['iso_path'] }} exists and that it is an iso."
    when: type is defined

  - fail:
      msg:
      - "!!! READ ME !!!"
      - "validate that {{ item['iso_path'] }} exists and that it is an iso."
    when: type is not defined

- name: "mounting {{ item['iso_path'] }} to {{ item['iso_mount_path'] }}"
  mount:
    path:   "{{ item['iso_mount_path'] }}"
    src:    "{{ item['iso_path'] }}"
    fstype: "iso9660"
    opts:  "ro,noauto"
    state: "mounted"

- name: "copy from iso mount to {{ foreman_server_url }}/pub/***"
  copy:
    remote_src: true
    src:  "{{ item['copy_path'] }}"
    dest: "{{ item['web_path'] }}"
    owner: apache
    group: apache
  when: item['web_path'] is defined

- include_tasks: copy.yml
  loop: "{{ item['kickstart_RHEL8_paths'] }}"
  when: item['kickstart_RHEL8_paths'] is defined
  loop_control:
    loop_var: path