- name: "Parsing a directory of partition templates"
  theforeman.foreman.partition_table:
    username: "{{ foreman_username }}"
    password: "{{ foreman_password }}"
    server_url: "{{ foreman_server_url }}"
    layout: "{{ lookup('file','disa_stig.erb') }}"
    state: present
    locations: 
    - "{{ foreman_location }}"
    organizations: 
    - "{{ foreman_organization }}"
