
- name: "create the web path: {{ item['web_path'] }}"
  file:
    path: "{{ item['web_path'] }}"
    recurse: true
    state: directory

- name: "verify  {{ item['iso_path'] }}"
  block:
  - stat: 
      path: "{{ item['iso_path'] }}"
      checksum: sha256
    register: iso_type
    ignore_errors: true

  - set_fact:
      test: "application/x-iso9660-image"
      type: "{{ iso_type['stat']['mimetype'] | default(omit) }}"

  - assert:
      that:
      - type == test
      msg:
      - "!!! READ ME !!!"
      - "validate that {{ item['iso_path'] }} exists and that it is an iso."
    when: type is defined

  - fail:
      msg:
      - "!!! READ ME !!!"
      - "validate that {{ item['iso_path'] }} exists and that it is an iso."
    when: type is not defined

- set_fact:
    line: "{{ last }},{{ checksum }},{{ size }}"
  vars:
    last: "{{ iso_type['stat']['path'] | split('/') | last }}"
    size: "{{ iso_type['stat']['size'] }}"
    checksum: "{{ iso_type['stat']['checksum'] }}"

- name: create {{ item['web_path'] }}/PULP_MANIFEST file
  lineinfile:
    path: "{{ item['web_path'] }}/PULP_MANIFEST"
    line: "{{ line }}"
    owner: apache
    group: apache
    create: true
    state: present
     
- name: copy {{ item['iso_path'] }} to {{ item['web_path'] }}
  copy:
    remote_src: true
    src:  "{{ item['iso_path'] }}"
    dest: "{{ item['web_path'] }}"
    owner: apache
    group: apache
