---
# tasks file for mount

- include_tasks: iso_path.yml     
  loop: "{{ __list | map(attribute='repositories') | flatten | selectattr('name','==', item) | selectattr('isos','defined') | map(attribute='isos') | list }}"
  vars:
    __list: "{{ _list | difference([foreman_products | last]) }}"
