ansible_user: root
foreman_username: admin
foreman_password: redhat
foreman_organization: hallas
foreman_validate_certs: false
foreman_server_url: "https://sat.example.net"

foreman_organizations:
- name:  "{{ foreman_organization }}"
  label: hallas
  state: present

foreman_domain:
- name: "example.net"
  location:
  - hallas
  organization:
  - "{{ foreman_organization }}"
