- hosts: all
  gather_facts: false
  collections:
  - theforeman.foreman
  - installer.kickstart
  tasks:

  - include_role:
      name: iso_repos
  - include_role:
      name: kickstart_content 
  - include_role:
      name: repositories 
