- hosts: all
  gather_facts: false
  collections:
  - theforeman.foreman
  - installer.kickstart
  tasks:
  - include_role:
      name: partition_table
  - include_role:
      name: operatingsystems 
