- include_tasks: iso_repos.yml
  loop_control:
    loop_var: repo
  with_subelements:
    - "{{ foreman_products | selectattr('repositories', 'defined') | list }}"
    - repositories
- include_tasks: validate_repos.yml
  with_items: "{{ foreman_products | selectattr('repositories', 'defined') | list }}"