- include_tasks: products.yml

- include_tasks: iso_repos.yml
  loop_control:
    loop_var: repo
  when: repo[1]['name'] not in repo_nogo
  with_subelements:
    - "{{ foreman_products | selectattr('repositories', 'defined') | list }}"
    - repositories

- include_role:
    name: installer.kickstart.iso_prep
  loop: "{{ repo_list }}"

- include_tasks: iso_sync.yml
  loop_control:
    loop_var: sync
  with_subelements:
    - "{{ foreman_products | selectattr('repositories', 'defined') | list }}"
    - repositories
