- name: 'Create Products'
  theforeman.foreman.product:
    username: "{{ foreman_username | default(omit) }}"
    password: "{{ foreman_password | default(omit) }}"
    server_url: "{{ foreman_server_url | default(omit) }}"
    validate_certs: "{{ foreman_validate_certs | default(omit) }}"
    organization: "{{ foreman_organization }}"
    name: "{{ item.name }}"
    label: "{{ item.label | default(omit) }}"
    gpg_key: "{{ item.gpg_key | default(omit) }}"
    state: present
  when: item['name'] not in product_nogo 
  with_items:
  - "{{ foreman_products | selectattr('repositories', 'defined') | list }}"
